sudo: required
dist: trusty
language: java
jdk:
    - openjdk7
    - oraclejdk8
    - oraclejdk9
env:
    - WLP_VERSION=18.0.0_01 WLP_LICENSE=L-CTUR-AVDTCN
    - WLP_VERSION=18.0.0_02 WLP_LICENSE=L-CTUR-AYBK6Z
script:
- travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=$WLP_VERSION -DwlpLicense=$WLP_LICENSE
