sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8
    - oraclejdk11
env:
    - WLP_VERSION=19.0.0_06 WLP_LICENSE=L-CTUR-BCTPHF
    - WLP_VERSION=19.0.0_09 WLP_LICENSE=L-CTUR-BEN4AJ
script:
    - travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=$WLP_VERSION -DwlpLicense=$WLP_LICENSE -e
