sudo: required
dist: trusty
language: java
jdk:
    - openjdk7
    - oraclejdk8
env:
    - WLP_VERSION=18.0.0_01 WLP_LICENSE=L-CTUR-AVDTCN
    - WLP_VERSION=17.0.0_04 WLP_LICENSE=L-SWIS-ASNMK6
script:
- travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=$WLP_VERSION -DwlpLicense=$WLP_LICENSE
